from fpdf import FPDF
import os

def generate_pdf(title, topic, num_pages):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=16)
    pdf.multi_cell(0, 10, f"Book Title: {title}\nAuthor: JarvisAI\n\nPowered by JarvisAI", align="C")
    
    for i in range(num_pages):
        pdf.add_page()
        pdf.set_font("Arial", size=12)
        pdf.multi_cell(0, 10, f"Page {i+1}\n\n{topic}\n\nGenerated by JarvisAI.", align="L")

    output_path = os.path.join("JarvisAI_Book.pdf")
    pdf.output(output_path)
    return output_path
